MathJax = {
    tex: {
        inlineMath: [['\\(','\\)']],
        macros: {
      calA: "{\\mathcal{A}}",
      calB: "{\\mathcal{B}}",
      calC: "{\\mathcal{C}}",
      calD: "{\\mathcal{D}}",
      calK: "{\\mathcal{K}}",
      calE: "{\\mathcal{E}}",
      calF: "{\\mathcal{F}}",
      calH: "{\\mathcal{H}}",
      calL: "{\\mathcal{L}}",
      calN: "{\\mathcal{N}}",
      calO: "{\\mathcal{O}}",
      calS: "{\\mathcal{S}}",
      calT: "{\\mathcal{T}}",
      calU: "{\\mathcal{U}}",
      calV: "{\\mathcal{V}}",
      calW: "{\\mathcal{W}}",
      calX: "{\\mathcal{X}}",
      calY: "{\\mathcal{Y}}",
      calZ: "{\\mathcal{Z}}",
      avgD: ["{\\mathbb{D}\\!\\left(#1\\Vert #2\\right)}",2],
      bfA: "{\\mathbf{A}}",
      bfB: "{\\mathbf{B}}",
      bfD: "{\\mathbf{D}}",
      bfG: "{\\mathbf{G}}",
      bfH: "{\\mathbf{H}}",
      bfI: "{\\mathbf{I}}",
      bfP: "{\\mathbf{P}}",
      bfQ: "{\\mathbf{Q}}",
      bfR: "{\\mathbf{R}}",
      bfS: "{\\mathbf{S}}",
      bfU: "{\\mathbf{U}}",
      bfV: "{\\mathbf{V}}",
      bfW: "{\\mathbf{W}}",
      bfX: "{\\mathbf{X}}",
      bfY: "{\\mathbf{Y}}",
      bfZ: "{\\mathbf{Z}}",
      bfone: "{\\mathbf{1}}",
      bfx: "{\\mathbf{x}}",
      bfr: "{\\mathbf{r}}",
      bfk: "{\\mathbf{k}}",
      bfm: "{\\mathbf{m}}",
      bfy: "{\\mathbf{y}}",
      bfu: "{\\mathbf{u}}",
      bfv: "{\\mathbf{v}}",
      bfw: "{\\mathbf{w}}",
      bfz: "{\\mathbf{z}}",
      bfb: "{\\mathbf{b}}",
      bfn: "{\\mathbf{n}}",
      bfzero: "{\\boldsymbol{0}}",
      bfalpha: "{\\boldsymbol{\\alpha}}",
      bfmu: "{\\boldsymbol{\\mu}}",
      bfbeta: "{\\boldsymbol{\\beta}}",
      bftheta: "{\\boldsymbol{\\theta}}",
      bfGamma: "{\\boldsymbol{\\Gamma}}",
      bfLambda: "{\\boldsymbol{\\Lambda}}",
      bfSigma: "{\\boldsymbol{\\Sigma}}",
      bfTheta: "{\\boldsymbol{\\Theta}}",
      bfI: "{\\mathbf{I}}",
      bfK: "{\\mathbf{K}}",
      bbK: "{\\mathbb{K}}",
      bbN: "{\\mathbb{N}}",
      bbR: "{\\mathbb{R}}",
      GF: ["\\mathbb{F}_{#1}",1],
      card: ["{|{#1}|}",1],
      abs: ["{\\left|{#1}\\right|}",1],
      sgn: ["{\\text{sgn}\\left({#1}\\right)}",1],
      norm: ["{\\left\\Vert{#2}\\right\\Vert}_{#1}",2,""],
      set: ["{\\{#1\\}}",1],
      trace: ["\\text{trace}\\left(#1\\right)",1],
      argmin: "\\mathop{\\text{argmin}}",
      argmax: "\\mathop{\\text{argmax}}",
      intseq: ["[{#1};{#2}]",2],
      eqdef: "\\triangleq",
      E: ["{\\mathbb{E}_{#1}\\!\\left[#2\\right]}",2,""],
      Var: ["{\\text{Var}(#1)}",1],
      P: ["{\\mathbb{P}_{#1}\\left(#2\\right)}",2,""],
      indic: ["{\\mathbf{1}\\{#1\\}}",1],
      bold: ["{\\bf #1}",1],
      mat: ["\\left[\\begin{array}{#1}#2\\end{array}\\right]",2],
      avgH: ["\\mathbb{H}\\!\\left(#1\\right)",1],
      avgI: ["\\mathbb{I}\\!\\left(#1\\right)",1],
      V : ["\\mathbb{V}\\left(#1\\right)",1],
      supp : ["\\text{supp}\\left(#1\\right)",1],
      dotp : ["\\langle #1,#2\\rangle",2]
    },
    },
    svg: {
        fontCache: 'global'
    },
};

MathJax.Hub.Config({
  "HTML-CSS": {
      preferredFont: "TeX",
      availableFonts: ["TeX"]
  },
  TeX: {
    Macros: {
      calA: "{\\mathcal{A}}",
      calB: "{\\mathcal{B}}",
      calC: "{\\mathcal{C}}",
      calD: "{\\mathcal{D}}",
      calK: "{\\mathcal{K}}",
      calE: "{\\mathcal{E}}",
      calF: "{\\mathcal{F}}",
      calH: "{\\mathcal{H}}",
      calL: "{\\mathcal{L}}",
      calN: "{\\mathcal{N}}",
      calO: "{\\mathcal{O}}",
      calS: "{\\mathcal{S}}",
      calT: "{\\mathcal{T}}",
      calU: "{\\mathcal{U}}",
      calV: "{\\mathcal{V}}",
      calW: "{\\mathcal{W}}",
      calX: "{\\mathcal{X}}",
      calY: "{\\mathcal{Y}}",
      calZ: "{\\mathcal{Z}}",
      avgD: ["{\\mathbb{D}\\!\\left(#1\\Vert #2\\right)}",2],
      bfA: "{\\mathbf{A}}",
      bfB: "{\\mathbf{B}}",
      bfD: "{\\mathbf{D}}",
      bfG: "{\\mathbf{G}}",
      bfH: "{\\mathbf{H}}",
      bfI: "{\\mathbf{I}}",
      bfP: "{\\mathbf{P}}",
      bfQ: "{\\mathbf{Q}}",
      bfR: "{\\mathbf{R}}",
      bfS: "{\\mathbf{S}}",
      bfU: "{\\mathbf{U}}",
      bfV: "{\\mathbf{V}}",
      bfW: "{\\mathbf{W}}",
      bfX: "{\\mathbf{X}}",
      bfY: "{\\mathbf{Y}}",
      bfZ: "{\\mathbf{Z}}",
      bfone: "{\\mathbf{1}}",
      bfx: "{\\mathbf{x}}",
      bfr: "{\\mathbf{r}}",
      bfk: "{\\mathbf{k}}",
      bfm: "{\\mathbf{m}}",
      bfy: "{\\mathbf{y}}",
      bfu: "{\\mathbf{u}}",
      bfv: "{\\mathbf{v}}",
      bfw: "{\\mathbf{w}}",
      bfz: "{\\mathbf{z}}",
      bfb: "{\\mathbf{b}}",
      bfn: "{\\mathbf{n}}",
      bfzero: "{\\boldsymbol{0}}",
      bfalpha: "{\\boldsymbol{\\alpha}}",
      bfmu: "{\\boldsymbol{\\mu}}",
      bfbeta: "{\\boldsymbol{\\beta}}",
      bftheta: "{\\boldsymbol{\\theta}}",
      bfGamma: "{\\boldsymbol{\\Gamma}}",
      bfLambda: "{\\boldsymbol{\\Lambda}}",
      bfSigma: "{\\boldsymbol{\\Sigma}}",
      bfTheta: "{\\boldsymbol{\\Theta}}",
      bfI: "{\\mathbf{I}}",
      bfK: "{\\mathbf{K}}",
      bbK: "{\\mathbb{K}}",
      bbN: "{\\mathbb{N}}",
      bbR: "{\\mathbb{R}}",
      GF: ["\\mathbb{F}_{#1}",1],
      card: ["{|{#1}|}",1],
      abs: ["{\\left|{#1}\\right|}",1],
      sgn: ["{\\text{sgn}\\left({#1}\\right)}",1],
      norm: ["{\\left\\Vert{#2}\\right\\Vert}_{#1}",2,""],
      set: ["{\\{#1\\}}",1],
      trace: ["\\text{trace}\\left(#1\\right)",1],
      argmin: "\\mathop{\\text{argmin}}",
      argmax: "\\mathop{\\text{argmax}}",
      intseq: ["[{#1};{#2}]",2],
      eqdef: "\\triangleq",
      E: ["{\\mathbb{E}_{#1}\\!\\left[#2\\right]}",2,""],
      Var: ["{\\text{Var}(#1)}",1],
      P: ["{\\mathbb{P}_{#1}\\left(#2\\right)}",2,""],
      indic: ["{\\mathbf{1}\\{#1\\}}",1],
      bold: ["{\\bf #1}",1],
      mat: ["\\left[\\begin{array}{#1}#2\\end{array}\\right]",2],
      avgH: ["\\mathbb{H}\\!\\left(#1\\right)",1],
      avgI: ["\\mathbb{I}\\!\\left(#1\\right)",1],
      V : ["\\mathbb{V}\\left(#1\\right)",1],
      supp : ["\\text{supp}\\left(#1\\right)",1]
    }
  }
});
